In [14]:
import pandas as pd

df = pd.read_csv('tyre_dataset.csv')
df

,Image,Brand,Compatible Vehicles,Price,Product Description,Features & Benefits,Vehicle Models
0,https://www.tyremarket.com/images/products/AMA...,Apollo Amazer 4G Life 165 80 R 14 Tubeless 85 ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","3,785",The Amazer series tyre 4G Life receives long t...,The Amazer 4G Life acquires extra long durabil...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
1,https://www.tyremarket.com/images/products/Ama...,Apollo Amazer 3G Maxx 165 80 R 14 Tubeless 85 ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","4,541",The asymmetric pattern tyre from Apollo is an ...,The Amazer 3G Maxx is a tyre with reliable and...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
2,https://www.tyremarket.com/images/products/AMA...,Apollo AMAZER XL 165 80 R 14 Tubeless 85 T Car...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","3,615",The Amazer XL is a renowned name in the mass s...,The Amazer XL is one of the first and longest ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
3,https://www.tyremarket.com/images/products/FS1...,Firestone FS100 165 80 R 14 Tubeless 83 T Car ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","3,837",Firestone FS100 is considered to be one of the...,The FS100 has been given chamfered edge so as ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
4,https://www.tyremarket.com/images/products/FR5...,Firestone FR500 165 80 R 14 Tubeless 85 T Car ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","3,499",Japanese tyre giant Bridgestone launched its F...,The wide shoulder grooves of Firestone FR500 p...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
...,...,...,...,...,...,...,...
13651,https://www.tyremarket.com/images/products/551...,UltraMile UM 551 205 65 R 16 Tubeless 95 H Ca...,"Hyundai Creta, Nissan Teana, Toyota Innova Crysta","6,409",The UM 551 is a very reliable tyre developed i...,Excellent water evacuation can be experienced ...,"Hyundai Creta, Nissan Teana, Toyota Innova Crysta"
13652,https://www.tyremarket.com/images/products/551...,UltraMile UM 551 205 65 R 16 Tubeless 95 H Ca...,"Hyundai Creta, Nissan Teana, Toyota Innova Crysta","6,409",The UM 551 is a very reliable tyre developed i...,Excellent water evacuation can be experienced ...,"Hyundai Creta, Nissan Teana, Toyota Innova Crysta"
13653,https://www.tyremarket.com/images/products/E70...,Yokohama DB E70B 215 55 R 17 Tubeless 93 V Car...,"Hyundai Sonata Transform, Maruti Kizashi, Niss...","20,257",Yokohama E70B is a premium touring summer tyre...,Four circumferential straight grooves provide ...,"Hyundai Sonata Transform, Maruti Kizashi, Niss..."
13654,https://www.tyremarket.com/images/products/E70...,Yokohama DB E70B 215 55 R 17 Tubeless 93 V Car...,"Hyundai Sonata Transform, Maruti Kizashi, Niss...","20,257",Yokohama E70B is a premium touring summer tyre...,Four circumferential straight grooves provide ...,"Hyundai Sonata Transform, Maruti Kizashi, Niss..."
13655,https://www.tyremarket.com/images/products/E70...,Yokohama DB E70B 215 55 R 17 Tubeless 93 V Car...,"Hyundai Sonata Transform, Maruti Kizashi, Niss...","20,257",Yokohama E70B is a premium touring summer tyre...,Four circumferential straight grooves provide ...,"Hyundai Sonata Transform, Maruti Kizashi, Niss..."

In [15]:
df = df.head(200)
df

,Image,Brand,Compatible Vehicles,Price,Product Description,Features & Benefits,Vehicle Models
0,https://www.tyremarket.com/images/products/AMA...,Apollo Amazer 4G Life 165 80 R 14 Tubeless 85 ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","3,785",The Amazer series tyre 4G Life receives long t...,The Amazer 4G Life acquires extra long durabil...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
1,https://www.tyremarket.com/images/products/Ama...,Apollo Amazer 3G Maxx 165 80 R 14 Tubeless 85 ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","4,541",The asymmetric pattern tyre from Apollo is an ...,The Amazer 3G Maxx is a tyre with reliable and...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
2,https://www.tyremarket.com/images/products/AMA...,Apollo AMAZER XL 165 80 R 14 Tubeless 85 T Car...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","3,615",The Amazer XL is a renowned name in the mass s...,The Amazer XL is one of the first and longest ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
3,https://www.tyremarket.com/images/products/FS1...,Firestone FS100 165 80 R 14 Tubeless 83 T Car ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","3,837",Firestone FS100 is considered to be one of the...,The FS100 has been given chamfered edge so as ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
4,https://www.tyremarket.com/images/products/FR5...,Firestone FR500 165 80 R 14 Tubeless 85 T Car ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...","3,499",Japanese tyre giant Bridgestone launched its F...,The wide shoulder grooves of Firestone FR500 p...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit..."
...,...,...,...,...,...,...,...
195,https://www.tyremarket.com/images/products/F1_...,Ceat Formula I Steel BT 215 75 R 15 Requires T...,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU...","5,581",CEAT Formula-I Steel BT is the quintessential ...,Longer tread life is ensured by chunkier block...,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU..."
196,https://www.tyremarket.com/images/products/F1_...,Ceat Formula I Steel BT 215 75 R 15 Requires T...,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU...","5,581",CEAT Formula-I Steel BT is the quintessential ...,Longer tread life is ensured by chunkier block...,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU..."
197,https://www.tyremarket.com/images/products/JK_...,JK Brute 215 75 R 15 Requires Tube 115 Car Tyre,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU...","7,549",JK Brute is a rugged SUV tyre designed to sust...,The computerised pattern and optimized footpri...,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU..."
198,https://www.tyremarket.com/images/products/JK_...,JK Brute 215 75 R 15 Requires Tube 115 Car Tyre,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU...","7,549",JK Brute is a rugged SUV tyre designed to sust...,The computerised pattern and optimized footpri...,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU..."
199,https://www.tyremarket.com/images/products/JK_...,JK Brute 215 75 R 15 Requires Tube 115 Car Tyre,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU...","7,549",JK Brute is a rugged SUV tyre designed to sust...,The computerised pattern and optimized footpri...,"Mahindra Bolero, Mahindra Scorpio, Mahindra TU..."

In [9]:

df.to_json('tyre_dataset.json', orient='records', lines=False, force_ascii=False)

In [12]:
import uuid

def generate_id(row):
    # Creating a simple unique ID using 'TYRE' + hex part of uuid4
    return f"TYRE_{uuid.uuid4().hex[:6].upper()}"

# Remove commas from the "Price" column and convert to float
df['Price'] = df['Price'].astype(str).str.replace(',', '').astype(float)

df['id'] = df.apply(generate_id, axis=1)
df.head()

,Image,Brand,Compatible Vehicles,Price,Product Description,Features & Benefits,Vehicle Models,id
0,https://www.tyremarket.com/images/products/AMA...,Apollo Amazer 4G Life 165 80 R 14 Tubeless 85 ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",3785.0,The Amazer series tyre 4G Life receives long t...,The Amazer 4G Life acquires extra long durabil...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",TYRE_1E414A
1,https://www.tyremarket.com/images/products/Ama...,Apollo Amazer 3G Maxx 165 80 R 14 Tubeless 85 ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",4541.0,The asymmetric pattern tyre from Apollo is an ...,The Amazer 3G Maxx is a tyre with reliable and...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",TYRE_620FDA
2,https://www.tyremarket.com/images/products/AMA...,Apollo AMAZER XL 165 80 R 14 Tubeless 85 T Car...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",3615.0,The Amazer XL is a renowned name in the mass s...,The Amazer XL is one of the first and longest ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",TYRE_F1E1D8
3,https://www.tyremarket.com/images/products/FS1...,Firestone FS100 165 80 R 14 Tubeless 83 T Car ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",3837.0,Firestone FS100 is considered to be one of the...,The FS100 has been given chamfered edge so as ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",TYRE_618264
4,https://www.tyremarket.com/images/products/FR5...,Firestone FR500 165 80 R 14 Tubeless 85 T Car ...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",3499.0,Japanese tyre giant Bridgestone launched its F...,The wide shoulder grooves of Firestone FR500 p...,"Fiat Grande Punto, Fiat Punto Pure, Maruti Rit...",TYRE_65F370

In [13]:
# Save the DataFrame (including the generated 'id' column) to a JSON file
df.to_json('tyre_dataset_with_id.json', orient='records', lines=False, force_ascii=False)